version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - "5439:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build: .
    environment:
      - PORT=3000
      - POSTGRES_URL=postgresql://postgres:123456@postgres:5432/postgres
      - MONGO_URL=mongodb://mongo:27017/logitech_v2
      - FILE_DATA_CSV=data/AM-prueba-desempeno-data.csv
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health" ]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  pgdata:
  mongodata:
